const timeTableList = [
  {
    img: "./images/timeTable01.jpg",
    sort: "TIME TABLE",
    title: "4~5월 그랑 조이 키즈 프로그램",
    date: "2022.04.01 - 2022.05.31",
    info: "액티비티 팀 그랑 조이와 함께 어린이 및 패밀리 고객이 즐겁게 즐길 수 있는 봄맞이 조선 주니어 키즈 프로그램입니다.",
    imgForOtherPrograms: "./images/timeTable01otherPrograms.jpg",
  },
  {
    img: "./images/timeTable02.jpg",
    sort: "TIME TABLE",
    title: "5월 그랑 조이 웰니스 프로그램",
    date: "2022.05.01 - 2022.05.31",
    info: "액티비티 팀 그랑 조이가 준비한 다양한 웰니스 프로그램을 통해 색다른 즐거움을 경험하세요.",
    imgForOtherPrograms: "./images/timeTable02otherPrograms.jpg",
  },
];
const josonJuniorForKidList = [
  {
    img: "./images/josonJuniorForKids01.jpg",
    sort: "JOSUN JUNIOR FOR KIDS",
    title: "그랑 조이 클레이 타임",
    date: "2022.04.01 - 2022.05.31",
    info: "매일 새로운 아이클레이 만들기로 아이의 소근육과 창의력을 키워주는 즐거운 클래스입니다.",
    imgForOtherPrograms: "./images/josonJuniorForKids01otherPrograms.jpg",
  },
  {
    img: "./images/josonJuniorForKids02.jpg",
    sort: "JOSUN JUNIOR FOR KIDS",
    title: "그랑 조이 키즈 스포츠",
    date: "2022.04.01 - 2022.05.31",
    info: "",
    imgForOtherPrograms: "./images/josonJuniorForKids02otherPrograms.jpg",
  },
  {
    img: "./images/josonJuniorForKids03.jpg",
    sort: "JOSUN JUNIOR FOR KIDS",
    title: "All Day 키즈 케어",
    date: "2022.04.01 - 2022.05.31",
    info: "아이들은 즐겁고 다양한 체험을 경험하고 부모님에게는 제주로운 힐링과 휴식을 선물해주는 프로그램입니다.",
    imgForOtherPrograms: "./images/josonJuniorForKids03otherPrograms.jpg",
  },
  {
    img: "./images/josonJuniorForKids04.jpg",
    sort: "JOSUN JUNIOR FOR KIDS",
    title: "그랑 조이 빙고놀이",
    date: "2022.04.01 - 2022.05.31",
    info: "그랑 조이와 함께하는 빙고타임! 빙고놀이에 참여하여 가장 먼저 빙고를 완성해보세요. ",
    imgForOtherPrograms: "./images/josonJuniorForKids04otherPrograms.jpg",
  },
  {
    img: "./images/josonJuniorForKids05.jpg",
    sort: "JOSUN JUNIOR FOR KIDS",
    title: "테라리움 만들기",
    date: "2022.04.01 - 2022.05.31",
    info: "흙과 여러가지 장식 소품을 넣고 식물을 가꾸어 나만의 화분을 만들어 보는 프로그램입니다. ",
    imgForOtherPrograms: "./images/josonJuniorForKids05otherPrograms.jpg",
  },
  {
    img: "./images/josonJuniorForKids06.jpg",
    sort: "JOSUN JUNIOR FOR KIDS",
    title: "쿠킹 클래스: 제주 흑돼지 피자 만들기",
    date: "2022.04.01 - 2022.05.31",
    info: "오늘은 내가 요리사! 사랑하는 엄마아빠를 위한 달콤한 디저트를 내 손으로 직접 만들어 보는 프로그램입니다.",
    imgForOtherPrograms: "./images/josonJuniorForKids06otherPrograms.jpg",
  },
  {
    img: "./images/josonJuniorForKids07.jpg",
    sort: "JOSUN JUNIOR FOR KIDS",
    title: "쿠킹 클래스: 딸기 케이크 만들기",
    date: "2022.04.01 - 2022.05.31",
    info: "오늘은 내가 요리사! 사랑하는 엄마아빠를 위한 달콤한 디저트를 내 손으로 직접 만들어 보는 프로그램입니다.",
    imgForOtherPrograms: "./images/josonJuniorForKids07otherPrograms.jpg",
  },
  {
    img: "./images/josonJuniorForKids08.jpg",
    sort: "JOSUN JUNIOR FOR KIDS",
    title: "새학기 달력 & 필통 만들기",
    date: "2022.04.01 - 2022.05.31",
    info: "새학기를 맞이하여 나만의 우드 달력과 다양한 장식 소품으로 필통을 만드는 프로그램입니다.",
    imgForOtherPrograms: "./images/josonJuniorForKids08otherPrograms.jpg",
  },
  {
    img: "./images/josonJuniorForKids09.jpg",
    sort: "JOSUN JUNIOR FOR KIDS",
    title: "키즈 스콜레 씽크잼",
    date: "2022.04.01 - 2022.05.31",
    info: "여러가지 재료들로 모양과 색을 표현하여 나만의 작품을 완성시키는 프로그램입니다.",
    imgForOtherPrograms: "./images/josonJuniorForKids09otherPrograms.jpg",
  },
  {
    img: "./images/josonJuniorForKids10.jpg",
    sort: "JOSUN JUNIOR FOR KIDS",
    title: "하바리움 만들기",
    date: "2022.04.01 - 2022.05.31",
    info: "투명한 병에 여러가지 꽃을 담아 나만의 꽃 아쿠아리움을 만들어 보는 프로그램입니다.",
    imgForOtherPrograms: "./images/josonJuniorForKids10otherPrograms.jpg",
  },
  {
    img: "./images/josonJuniorForKids11.jpg",
    sort: "JOSUN JUNIOR FOR KIDS",
    title: "조선 주니어 에코백 만들기",
    date: "2022.04.01 - 2022.05.31",
    info: "알록달록 물감을 이용하여 에코백과 열쇠고리를 만들어 보는 프로그램입니다.",
    imgForOtherPrograms: "./images/josonJuniorForKids11otherPrograms.jpg",
  },
];
const adultList = [
  {
    img: "./images/adult01.jpg",
    sort: "ADULT",
    title: "그랑 조이 스냅",
    date: "2022.04.01 - 2022.05.31",
    info: "그랑 조이가 추천하는 스팟 3곳에서 최고의 사진을 남겨드립니다.",
    imgForOtherPrograms: "./images/adult01otherPrograms.jpg",
  },
  {
    img: "./images/adult02.jpg",
    sort: "ADULT",
    title: "원 포인트 스윔 레슨",
    date: "2022.04.01 - 2022.05.31",
    info: "물과 친해지는 방법, 평소 배우고 싶었던 영법을 알려드리는 프로그램입니다.",
    imgForOtherPrograms: "./images/adult02otherPrograms.jpg",
  },
  {
    img: "./images/adult03.jpg",
    sort: "ADULT",
    title: "플로팅 요가",
    date: "2022.04.01 - 2022.05.31",
    info: "물 위에서 균형 감각을 깨워주며 색다른 요가 체험을 할 수 있는 프로그램입니다.",
    imgForOtherPrograms: "./images/adult03otherPrograms.jpg",
  },
  {
    img: "./images/adult04.jpg",
    sort: "ADULT",
    title: "홈 필라테스 With. CHA:E 차이 ",
    date: "2022.04.01 - 2022.05.31",
    info: "홈 필라테스 브랜드 'CHA:E(차이)'와 함께 나를 위한 '쉼'을 선물하는 액티비티 프로그램입니다.",
    imgForOtherPrograms: "./images/adult04otherPrograms.jpg",
  },
  {
    img: "./images/adult05.jpg",
    sort: "ADULT",
    title: "나만의 향수 만들기",
    date: "2022.04.01 - 2022.05.31",
    info: "80여가지 조향 원료로 각자의 취향에 대해 알아보고 블렌딩하여 나만의 향수를 만들어보는 프로그램입니다.",
    imgForOtherPrograms: "./images/adult05otherPrograms.jpg",
  },
  {
    img: "./images/adult06.jpg",
    sort: "ADULT",
    title: "스머지 스틱 만들기",
    date: "2022.04.01 - 2022.05.31",
    info: "제주 허브 다발을 이용한 천연 인센스 방향제 만들기 프로그램입니다.",
    imgForOtherPrograms: "./images/adult06otherPrograms.jpg",
  },
];
const allList = josonJuniorForKidList.concat(adultList.concat(timeTableList));
